"""empty message

Revision ID: 4e1594dbb073
Revises: 76ab1e4f9d54
Create Date: 2025-11-17 20:26:41.787972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1594dbb073'
down_revision = '76ab1e4f9d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_films',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('peoples', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['peoples'], ['films.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.create_table('favorites_peoples',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('peoples', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['peoples'], ['peoples.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.create_table('favorites_planets',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('peoples', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['peoples'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.create_table('favorites_vehicles',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('peoples', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['peoples'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_vehicles')
    op.drop_table('favorites_planets')
    op.drop_table('favorites_peoples')
    op.drop_table('favorites_films')
    # ### end Alembic commands ###
